### PR TITLE
Create the Json Schema lexer using pygments

### PR DESCRIPTION
**Pull request by sudo-jarvis**
This pull request implements the JSON Schema lexer functionality discussed in bowtie-json-schema/bowtie#863.

### CODE REVIEW

**Comment by sudo-jarvis** [comment]
Hi @Julian , please have a look.

**Comment by Julian** [comment]
I'll take a closer look at this in a bit but I'm surprised you went with the regex lexer rather than building on top of (I assume an existing) JSON one.

That probably makes it quite a bit harder to know when something isn't a keyword at all, which is why in your screenshot you had keywords being highlighted even though they were inside string descriptions.

Did you not find anything in pygments for building on the existing JSON stuff?

**Comment by sudo-jarvis** [comment]
Also, currently the list of keywords being used are static and are from the latest dialect. I am not sure how to support multiple dialects

**Comment by sudo-jarvis** [comment]
This was the JSON lexer that I used for reference: https://github.com/orb/pygments-json

**Comment by Julian** [comment]
That project has no license! We definitely cannot use it or build on top of it without one!

**Comment by Julian** [comment]
Now that I'm back at a computer, yeah, what's wrong with the Pygments [JSON lexer](https://pygments.org/docs/lexers/#pygments.lexers.data.JsonLexer) that made you look for something else? I would assume what we'd use should be quite similar to e.g. the [JSON-LD lexer which builds on top of the JSON one](https://github.com/pygments/pygments/blob/26ffe8f472d18ed190a5ced00335682c618037d4/pygments/lexers/data.py#L717).

**Comment by sudo-jarvis** [comment]
> That project has no license! We definitely cannot use it or build on top of it without one!

I am sorry, I wasnt aware of this

**Comment by sudo-jarvis** [comment]
> Now that I'm back at a computer, yeah, what's wrong with the Pygments [JSON lexer](https://pygments.org/docs/lexers/#pygments.lexers.data.JsonLexer) that made you look for something else? I would assume what we'd use should be quite similar to e.g. the [JSON-LD lexer which builds on top of the JSON one](https://github.com/pygments/pygments/blob/26ffe8f472d18ed190a5ced00335682c618037d4/pygments/lexers/data.py#L717).

When I searched for the pygments JSON lexer, actually this result popped up at the top and I misunderstood it to be the actual lexer that pygemnts use. I am sorry for that, my bad.

**Comment by sudo-jarvis** [comment]
@Julian , you were right, working on top of the existing JSON lexer is much easier, just need to perform the list of keywords and stuff to it and it handles all the hardlifting. 

Thanks a lot and sorry again for not picking this very approach in the beginning itself

**Comment by sudo-jarvis** [comment]
With this too, the rest of the cases work fine however it misbehaves when encountering `\"` within a string.

Tried it with the metaschema for `2020-12 dialect`:

**1. JSON Schema lexer on top of JSON lexer:**
Screenshot 2024-02-28 at 10 33 32 AM

**2. Simple JSON lexer:**
Screenshot 2024-02-28 at 10 33 44 AM

**Pull request merged**
